- name: Add postgres repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main' state=present

- name: Add postgres repository key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present 

- name: Install postgresql
  apt: pkg=postgresql-{{ postgre_version }} state=present force=yes

- name: Start postgresql server
  service: name=postgresql state=started enabled=yes
  ignore_errors: True

- name: Install Packages
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - python-dev
    - python-setuptools
    - python-psycopg2
    - postgresql-contrib-{{ postgre_version }}
    - postgresql-{{ postgre_version }}-postgis-{{ postgis_version }}
    - libpq-dev
    - postgresql-9.5-pgrouting

## CREATE  EXTENSION pgrouting;
## SELECT * FROM pgr_version();

# based on https://trac.osgeo.org/postgis/wiki/UsersWikiPostGIS15Ubuntu1110src

- name: ensure template_postgis database exists
  become: yes
  become_user: postgres
  postgresql_db: name=postgis_template state=present
  register: createdb_template_postgis

- name: make postgis_template
  become: yes
  become_user: postgres
  command: psql -d postgis_template -c "UPDATE pg_database SET datistemplate=true WHERE datname='postgis_template';"
  when: createdb_template_postgis.changed

- name: enable postgis extension 
  become: yes
  become_user: postgres
  command: psql -d postgis_template -c "CREATE EXTENSION postgis;"
  when: createdb_template_postgis.changed

#- name: run the postgis SQL scripts
#  become: yes
#  become_user: postgres
#  command: psql -d postgis_template -f {{ item }}
#  with_items:
#    - /usr/share/postgresql/{{ postgre_version }}/contrib/postgis-{{ postgis_version }}/postgis.sql
#    - /usr/share/postgresql/{{ postgre_version }}/contrib/postgis-{{ postgis_version }}/spatial_ref_sys.sql
#    - /usr/share/postgresql/{{ postgre_version }}/contrib/postgis-{{ postgis_version }}/postgis_comments.sql
